openapi: 3.0.0
info:
  description: Test project for Effective Mobile.
  title: Subscription Microservice API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /subscriptions:
    get:
      summary: Get subscriptions
      description: Returns either a single subscription or list of subscriptions based on query parameters. If single subscription is requested the id parameter needs to be present and list parameter needs to be false. Otherwise, the list parameter needs to be set to true
      operationId: getSubscriptions
      parameters:
        - name: list
          in: query
          description: If true, returns list of all subscriptions. If not present, defaults to false.
          schema:
            type: boolean
          required: false
        - name: id
          in: query
          description: ID of a specific subscription to retrieve
          schema:
            type: integer
            format: int64
          required: false
      responses:
        '200':
          description: Successfully retrieved subscription(s)
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/SubscriptionResponse'
                  - $ref: '#/components/schemas/SubscriptionResponseList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new subscription
      description: Creates a database entry with given parameters
      operationId: createSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionRequest'
      responses:
        '201':
          description: Subscription created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a subscription
      description: Updates the database entry with given id
      operationId: updateSubscription
      parameters:
        - name: id
          in: query
          description: The ID of the subscription to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequest'
      responses:
        '200':
          description: Subscription updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a subscription
      description: Deletes a database entry with given id
      operationId: deleteSubscription
      parameters:
        - name: id
          in: query
          description: The ID of the subscription to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Subscription deleted successfully
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /subscriptions/sum:
    get:
      summary: Get subscriptions sum
      description: Returns a sum of subscriptions from given time period. There is an option for filtering subscriptions by user td and service name.
      operationId: getSubscriptionsSum
      parameters:
        - name: id
          in: query
          description: The ID of a user to filter by
          schema:
            type: string
      responses:
        '200':
          description: Subscription deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sum'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CustomTime:
      type: string
      format: date
      example: "08-2025"

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message details
      required:
        - error

    CreateSubscriptionRequest:
      type: object
      properties:
        service_name:
          type: string
          description: The name of the service
        price:
          type: integer
          format: int64
          description: The price of the subscription
        user_id:
          type: string
          description: The UUID of the user
        start_date:
          $ref: '#/components/schemas/CustomTime'
        end_date:
          $ref: '#/components/schemas/CustomTime'
      required:
        - service_name
        - price
        - user_id
        - start_date

    UpdateSubscriptionRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The id of a subscription in database
        service_name:
          type: string
          description: The name of the service
        price:
          type: integer
          format: int64
          description: The price of the subscription
        user_id:
          type: string
          description: The UUID of the user
        start_date:
          $ref: '#/components/schemas/CustomTime'
        end_date:
          $ref: '#/components/schemas/CustomTime'
      required:
        - id

    SubscriptionResponse:
      type: object
      description: The response, containing single subscription's data
      properties:
        id:
          type: integer
          format: int64
        service_name:
          type: string
        price:
          type: integer
          format: int64
        user_id:
          type: string
        start_date:
          $ref: '#/components/schemas/CustomTime'
        end_date:
          $ref: '#/components/schemas/CustomTime'

    SubscriptionResponseList:
      type: array
      items:
        $ref: '#/components/schemas/SubscriptionResponse'
    Sum:
      type: object
      properties:
        sum:
          type: integer
          format: int64
